In [88]:
import pandas as pd
from scipy.stats import chi2_contingency
from scipy.stats import chi2
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [89]:
# General Purpose Crosstab Generator (GPCG)

def dataRead(File):
    
    global data
    global data2
    data = pd.read_csv(File)
    
#     data = data[data.age == '55 and over']
#     data = data[data.gender == 'Female']
#     data = data[data.engager == "No"]

    global y
    y = data['engager']
    
dataRead("nbcu_ulta.csv")

In [433]:
data.age.value_counts()

55 and over    43
Name: age, dtype: int64

In [25]:
# Notes

# To get row names, useful for re-indexing
# df.index.values

# for x in type1(data.age, 0).index.values:
#     print(x)

In [223]:
type1(data.gender)

engager                 Control  Exposed  % Vertical (Control)  % Vertical (Exposed)
gender
Female                      167      178                  0.58                  0.43
Male                        118      235                  0.41                  0.57
Other / Rather not say        3        0                  0.01                  0.00
All                         288      413                  1.00                  1.00

# RUN THESE CELLS

In [3]:
def type1(x):
    a = pd.crosstab(x, y, margins=True)
    a['Non-Engaged'] = a['No']
    a['Engaged'] = a['Yes']
    a['% Vertical (Non-Engaged)'] = (a['No']*2/a['No'].sum()).round(2)
    a['% Vertical (Engaged)'] = (a['Yes']*2/a['Yes'].sum()).round(2)
    a = a.drop('No',axis=1)
    a = a.drop('Yes',axis=1)
    a = a.drop('All', axis = 1)
    a = a.fillna(0)
    a.to_clipboard(excel=True)
    return(a)

In [4]:
def type4(x):
    a = pd.crosstab(x, y, margins=True)
    a['Non-Engaged'] = a['No']
    a['Engaged'] = a['No']*0
    a['% Vertical (Non-Engaged)'] = (a['No']*2/a['No'].sum()).round(2)
    a['% Vertical (Engaged)'] = a['No']*0
    a = a.drop('No',axis=1)
    a = a.drop('All', axis = 1)
    a = a.fillna(0)
    a.to_clipboard(excel=True)
    return(a)

In [5]:
def type2(x):
    a = pd.crosstab(x, y, margins=False)
    return(a)

In [6]:
def type3(a,b):
    c = pd.crosstab(a,b, margins=False)
    return(c)

In [7]:
def concatType1(aList):
    group = []
    keyGroup = []
    for element in aList:
        group.append(type1(element[0]))
        keyGroup.append(element[1])
    
    result = pd.concat(group, keys = keyGroup, axis = 1)
    
    result = result.fillna(0)
    result.to_clipboard(excel=True)
    return(result)
    
    

# concatType1([(data.q6_DiscoveryCove,'DiscoveryCove'),(data.q6_SeaWorld, 'SeaWorld'),
#              (data.q6_Disney, 'Disney'),(data.q6_Universal,'Universal')])

In [8]:
def concatType4(aList):
    group = []
    keyGroup = []
    for element in aList:
        group.append(type4(element[0]))
        keyGroup.append(element[1])
    
    result = pd.concat(group, keys = keyGroup, axis = 1)
    
    result = result.fillna(0)
    result.to_clipboard(excel=True)
    return(result)

In [9]:
def breakdown(x, aList):
    b = len(aList)
    x = x.append(x.iloc[0:2,:].sum(axis = 0),ignore_index=True)
    x = x.append(x.iloc[b-3:b-1,:].sum(axis = 0),ignore_index=True)

    aDict = {}
    for y in range(b):
        aDict[y] = aList[y]
    aDict[b] = "Top 2"
    aDict[b+1] = "Bottom 2"
    x = x.rename(index = aDict)

    newList = [aList[0], aList[1], "Top 2"] + aList[2:b-1] + ["Bottom 2", "All"]
    x = x.reindex(newList)
    x = x.fillna(0)

    x.to_clipboard(excel=True)
    return(x)

In [10]:
def append(aList):
    result = type2(aList[0])
    for unit in range(1,len(aList)):
        result = result.append(type2(aList[unit]))
          
    result['Non-Engaged'] = result['No']
    result['Engaged'] = result['Yes']
    result = result.drop('No',axis=1)
    result = result.drop('Yes',axis=1)
    result = result.fillna(0)
    
    result.to_clipboard(excel=True)
    return(result)
    
    
# append([data.q10_dolphins, data.q10_fish, data.q10_rivers, 
#        data.q10_birds, data.q10_beach, data.q10_amenties, data.q10_none])

In [11]:
def append2(aList,y):
    result = type3(aList[0],y)
    for unit in range(1,len(aList)):
        result = result.append(type3(aList[unit], y))
    result = result.fillna(0)
    
    result.to_clipboard(excel=True)
    return(result)
    
    
# append([data.q10_dolphins, data.q10_fish, data.q10_rivers, 
#        data.q10_birds, data.q10_beach, data.q10_amenties, data.q10_none])

In [12]:
def p_val(val):
    if val < 0.05:
        return "<0.05"
    elif val < 0.1:
        return "<0.1"
    elif val < 0.15:
        return "<0.15"
    else:
        return ">0.15"

# FINISH

In [118]:
a = type1(data.gender)
a = a.reindex(["Male", "Female","Other/ Rather not say", "All"])
a = a.fillna(0)
a.to_clipboard(excel = True)
a

engager                Non-Engaged  Engaged  % Vertical (Non-Engaged)  % Vertical (Engaged)
gender
Male                           0.0      0.0                      0.00                   0.0
Female                       257.0    254.0                      0.99                   1.0
Other/ Rather not say          3.0      1.0                      0.01                   0.0
All                          260.0    255.0                      1.00                   1.0

In [120]:
a = type1(data.age)
a = a.reindex(["18 - 29","30 - 39", "40 - 49", "All"])
a = a.fillna(0)
a.to_clipboard(excel = True)
a

engager  Non-Engaged  Engaged  % Vertical (Non-Engaged)  % Vertical (Engaged)
age
18 - 29           79      108                       0.3                  0.42
30 - 39          104      107                       0.4                  0.42
40 - 49           77       40                       0.3                  0.16
All              260      255                       1.0                  1.00

In [121]:
a = concatType1([(data.q3_ult, "Ulta Beauty"), (data.q3_sep, "Sephora"), (data.q3_mac, "Macy's"), (data.q3_tar, "Target"), (data.q3_ama, "Amazon"), (data.q3_walm, "Walmart"), (data.q3_walg, "Walgreens")])
a = a.reindex(["Very Familiar", "Somewhat Familiar", "Heard of it but not familiar", "Never heard about this brand", "All"])
a = a.fillna(0)
a.to_clipboard(excel = True)
a

                             Ulta Beauty                                                           Sephora                                                            Macy's                                                            Target                                                            Amazon                                                           Walmart                                                         Walgreens
engager                      Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged)
Very Familiar                        120     145                     0.46                 0.57         123     139                     0.47                 0.55         152     175                     0.58                 0.69         225     213                     0.87                 0.84         242     221                     0.93                 0.87         227     200                     0.87                 0.78         180     156                     0.69                 0.61
Somewhat Familiar                     79      66                     0.30                 0.26          87      70                     0.33                 0.27          77      55                     0.30                 0.22          31      19                     0.12                 0.07          17      14                     0.07                 0.05          30      30                     0.12                 0.12          67      53                     0.26                 0.21
Heard of it but not familiar          46      36                     0.18                 0.14          46      38                     0.18                 0.15          29      21                     0.11                 0.08           4      18                     0.02                 0.07           1      17                     0.00                 0.07           3      18                     0.01                 0.07          10      39                     0.04                 0.15
Never heard about this brand          15       8                     0.06                 0.03           4       8                     0.02                 0.03           2       4                     0.01                 0.02           0       5                     0.00                 0.02           0       3                     0.00                 0.01           0       7                     0.00                 0.03           3       7                     0.01                 0.03
All                                  260     255                     1.00                 1.00         260     255                     1.00                 1.00         260     255                     1.00                 1.00         260     255                     1.00                 1.00         260     255                     1.00                 1.00         260     255                     1.00                 1.00         260     255                     1.00                 1.00

In [122]:
a = concatType1([(data.q4_ult, "Ulta Beauty"), (data.q4_sep, "Sephora"), (data.q4_mac, "Macy's"), (data.q4_tar, "Target"), (data.q4_ama, "Amazon"), (data.q4_walm, "Walmart"), (data.q4_walg, "Walgreens")])
a = a.reindex(["Very Favorable", "Somewhat Favorable", "Neutral", "Somewhat Unfavorable", "Very Unfavorable", "All"])
a = breakdown(a,["Very Favorable", "Somewhat Favorable", "Neutral", "Somewhat Unfavorable", "Very Unfavorable", "All"] )
a = a.fillna(0)
a.to_clipboard(excel = True)
a

/Users/chrisferandel/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:8: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

                     Ulta Beauty                                                           Sephora                                                            Macy's                                                            Target                                                            Amazon                                                           Walmart                                                         Walgreens
engager              Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged)
Very Favorable              84.0   114.0                     0.42                 0.54        82.0   100.0                     0.39                 0.48        60.0    90.0                     0.26                 0.39       145.0   133.0                     0.57                 0.57       170.0   160.0                     0.66                 0.68        84.0   100.0                     0.33                 0.43        59.0    58.0                     0.24                 0.28
Somewhat Favorable          77.0    69.0                     0.39                 0.33        75.0    65.0                     0.36                 0.31        99.0    77.0                     0.43                 0.33        80.0    64.0                     0.31                 0.28        60.0    48.0                     0.23                 0.20        79.0    79.0                     0.31                 0.34        96.0    91.0                     0.39                 0.44
Top 2                      161.0   183.0                     0.81                 0.87       157.0   165.0                     0.75                 0.79       159.0   167.0                     0.69                 0.72       225.0   197.0                     0.88                 0.85       230.0   208.0                     0.89                 0.88       163.0   179.0                     0.64                 0.77       155.0   149.0                     0.63                 0.72
Neutral                     33.0    21.0                     0.17                 0.10        39.0    36.0                     0.19                 0.17        58.0    49.0                     0.25                 0.21        24.0    29.0                     0.09                 0.12        12.0    17.0                     0.05                 0.07        38.0    25.0                     0.15                 0.11        76.0    51.0                     0.31                 0.24
Somewhat Unfavorable         4.0     5.0                     0.02                 0.02        12.0     8.0                     0.06                 0.04        12.0    14.0                     0.05                 0.06         6.0     5.0                     0.02                 0.02        14.0     9.0                     0.05                 0.04        35.0    16.0                     0.14                 0.07        14.0     9.0                     0.06                 0.04
Very Unfavorable             1.0     2.0                     0.01                 0.01         2.0     0.0                     0.01                 0.00         0.0     0.0                     0.00                 0.00         1.0     1.0                     0.00                 0.00         3.0     1.0                     0.01                 0.00        21.0    10.0                     0.08                 0.04         2.0     0.0                     0.01                 0.00
Bottom 2                     5.0     7.0                     0.03                 0.03        14.0     8.0                     0.07                 0.04        12.0    14.0                     0.05                 0.06         7.0     6.0                     0.02                 0.02        17.0    10.0                     0.06                 0.04        56.0    26.0                     0.22                 0.11        16.0     9.0                     0.07                 0.04
All                        199.0   211.0                     1.00                 1.00       210.0   209.0                     1.00                 1.00       229.0   230.0                     1.00                 1.00       256.0   232.0                     1.00                 1.00       259.0   235.0                     1.00                 1.00       257.0   230.0                     1.00                 1.00       247.0   209.0                     1.00                 1.00

In [123]:
a = concatType1([(data.q5_ult, "Ulta Beauty"), (data.q5_sep, "Sephora"), (data.q5_mac, "Macy's"), (data.q5_tar, "Target"), (data.q5_ama, "Amazon"), (data.q5_walm, "Walmart"), (data.q5_walg, "Walgreens")])
a = a.reindex(["Very Likely", "Somewhat Likely", "Neutral", "Somewhat Unlikely", "Very Unlikely", "All"])
a = breakdown(a,["Very Likely", "Somewhat Likely", "Neutral", "Somewhat Unlikely", "Very Unlikely", "All"] )
a = a.fillna(0)
a.to_clipboard(excel = True)
a

                  Ulta Beauty                                                           Sephora                                                            Macy's                                                            Target                                                            Amazon                                                           Walmart                                                         Walgreens
engager           Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged)
Very Likely              75.0    95.0                     0.38                 0.45        61.0    69.0                     0.29                 0.33        24.0    48.0                     0.10                 0.21        88.0   104.0                     0.34                 0.45        96.0   121.0                     0.37                 0.51        94.0    99.0                     0.37                 0.43        45.0    51.0                     0.18                 0.24
Somewhat Likely          60.0    75.0                     0.30                 0.36        64.0    52.0                     0.30                 0.25        45.0    39.0                     0.20                 0.17        84.0    70.0                     0.33                 0.30        87.0    64.0                     0.34                 0.27        63.0    69.0                     0.25                 0.30        64.0    56.0                     0.26                 0.27
Top 2                   135.0   170.0                     0.68                 0.81       125.0   121.0                     0.59                 0.58        69.0    87.0                     0.30                 0.38       172.0   174.0                     0.67                 0.75       183.0   185.0                     0.71                 0.78       157.0   168.0                     0.62                 0.73       109.0   107.0                     0.44                 0.51
Neutral                  26.0    16.0                     0.13                 0.08        25.0    48.0                     0.12                 0.23        37.0    73.0                     0.16                 0.32        34.0    35.0                     0.13                 0.15        27.0    20.0                     0.10                 0.09        34.0    30.0                     0.13                 0.13        62.0    59.0                     0.25                 0.28
Somewhat Unlikely        21.0    15.0                     0.11                 0.07        37.0    23.0                     0.18                 0.11        72.0    40.0                     0.31                 0.17        28.0    18.0                     0.11                 0.08        34.0    24.0                     0.13                 0.10        30.0    23.0                     0.12                 0.10        42.0    23.0                     0.17                 0.11
Very Unlikely            17.0    10.0                     0.09                 0.05        23.0    17.0                     0.11                 0.08        51.0    30.0                     0.22                 0.13        22.0     5.0                     0.09                 0.02        15.0     6.0                     0.06                 0.03        36.0     9.0                     0.14                 0.04        34.0    20.0                     0.14                 0.10
Bottom 2                 38.0    25.0                     0.20                 0.12        60.0    40.0                     0.29                 0.19       123.0    70.0                     0.53                 0.30        50.0    23.0                     0.20                 0.10        49.0    30.0                     0.19                 0.13        66.0    32.0                     0.26                 0.14        76.0    43.0                     0.31                 0.21
All                     199.0   211.0                     1.00                 1.00       210.0   209.0                     1.00                 1.00       229.0   230.0                     1.00                 1.00       256.0   232.0                     1.00                 1.00       259.0   235.0                     1.00                 1.00       257.0   230.0                     1.00                 1.00       247.0   209.0                     1.00                 1.00

In [124]:
a = concatType1([(data.q6_ult, "Ulta Beauty"), (data.q6_sep, "Sephora"), (data.q6_mac, "Macy's"), (data.q6_tar, "Target"), (data.q6_ama, "Amazon"), (data.q6_walm, "Walmart"), (data.q6_walg, "Walgreens")])
a = a.reindex(["Very Likely", "Somewhat Likely", "Neutral", "Somewhat Unlikely", "Very Unlikely", "All"])
a = breakdown(a,["Very Likely", "Somewhat Likely", "Neutral", "Somewhat Unlikely", "Very Unlikely", "All"] )
a = a.fillna(0)
a.to_clipboard(excel = True)
a

                  Ulta Beauty                                                           Sephora                                                            Macy's                                                            Target                                                            Amazon                                                           Walmart                                                         Walgreens
engager           Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged)
Very Likely              82.0   108.0                     0.41                 0.51        84.0    76.0                     0.40                 0.36        53.0    63.0                     0.23                 0.27       112.0   119.0                     0.44                 0.51       143.0   139.0                     0.55                 0.59        81.0    83.0                     0.32                 0.36        47.0    61.0                     0.19                 0.29
Somewhat Likely          57.0    64.0                     0.29                 0.30        56.0    58.0                     0.27                 0.28        58.0    51.0                     0.25                 0.22        81.0    53.0                     0.32                 0.23        62.0    57.0                     0.24                 0.24        61.0    70.0                     0.24                 0.30        69.0    61.0                     0.28                 0.29
Top 2                   139.0   172.0                     0.70                 0.81       140.0   134.0                     0.67                 0.64       111.0   114.0                     0.48                 0.49       193.0   172.0                     0.76                 0.74       205.0   196.0                     0.79                 0.83       142.0   153.0                     0.56                 0.66       116.0   122.0                     0.47                 0.58
Neutral                  40.0    24.0                     0.20                 0.11        41.0    53.0                     0.20                 0.25        68.0    78.0                     0.30                 0.34        41.0    37.0                     0.16                 0.16        32.0    24.0                     0.12                 0.10        50.0    37.0                     0.19                 0.16        86.0    53.0                     0.35                 0.25
Somewhat Unlikely         9.0     6.0                     0.05                 0.03        16.0    13.0                     0.08                 0.06        27.0    22.0                     0.12                 0.10        14.0    16.0                     0.05                 0.07        14.0    11.0                     0.05                 0.05        30.0    19.0                     0.12                 0.08        28.0    19.0                     0.11                 0.09
Very Unlikely            11.0     9.0                     0.06                 0.04        13.0     9.0                     0.06                 0.04        23.0    16.0                     0.10                 0.07         8.0     7.0                     0.03                 0.03         8.0     4.0                     0.03                 0.02        35.0    21.0                     0.14                 0.09        17.0    15.0                     0.07                 0.07
Bottom 2                 20.0    15.0                     0.11                 0.07        29.0    22.0                     0.14                 0.10        50.0    38.0                     0.22                 0.17        22.0    23.0                     0.08                 0.10        22.0    15.0                     0.08                 0.07        65.0    40.0                     0.26                 0.17        45.0    34.0                     0.18                 0.16
All                     199.0   211.0                     1.00                 1.00       210.0   209.0                     1.00                 1.00       229.0   230.0                     1.00                 1.00       256.0   232.0                     1.00                 1.00       259.0   235.0                     1.00                 1.00       257.0   230.0                     1.00                 1.00       247.0   209.0                     1.00                 1.00

In [125]:
a = append([data.q7_ult, data.q7_sep, data.q7_mac, data.q7_tar, data.q7_ama, data.q7_walm, data.q7_walg])
a = a.reindex(['Ulta Beauty', 'Sephora', "Macy's", "Target", "Amazon", "Walmart", "Walgreens"])
a = a.fillna(0)
a.to_clipboard(excel = True)
a

engager      Non-Engaged  Engaged
Ulta Beauty           63      104
Sephora               66      106
Macy's                44       91
Target               102      111
Amazon               149      160
Walmart               87      106
Walgreens             21       30

In [127]:
a = type1(data.q8)
a = a.reindex(["It is more favorable", "It is somewhat more favorable", "My opinion of brand remains the same", "It is somewhat less favorable", "All"])
a = a.fillna(0)
a.to_clipboard(excel = True)
a

engager                               Non-Engaged  Engaged  % Vertical (Non-Engaged)  % Vertical (Engaged)
q8
It is more favorable                           16       68                      0.25                  0.65
It is somewhat more favorable                   9       18                      0.14                  0.17
My opinion of brand remains the same           37       18                      0.59                  0.17
It is somewhat less favorable                   1        0                      0.02                  0.00
All                                            63      104                      1.00                  1.00

In [129]:
a = append([data.q9a, data.q9b, data.q9c, data.q9d, data.q9e, data.q9f, data.q9g, data.q9h, data.q9i, data.q9j, data.q9k, data.q9l, data.q9m, data.q9n, data.q9o, data.q9p, data.q9q, data.q9r, data.q9s, data.q9t])
a = a.reindex(['Approachable', 'Confident', 'Exciting', 'Inspiring', 'Judgmental', 'Knowledgeable/Expert', 'Welcoming', 'Trustworthy', 'Unique', 'Snobby', 'Authentic', 'Youthful', 'Boring', 'On-Trend', 'Fun', 'Empowering', 'Leader', 'Popular', 'Inclusive', 'None of the Above'])
a = a.fillna(0)
a.to_clipboard(excel = True)
a

engager               Non-Engaged  Engaged
Approachable                   68       56
Confident                      75       77
Exciting                       56       69
Inspiring                      33       67
Judgmental                     15       22
Knowledgeable/Expert           76       70
Welcoming                      70       76
Trustworthy                    56       77
Unique                         48       82
Snobby                         39       23
Authentic                      50       50
Youthful                      102      103
Boring                          6        7
On-Trend                      150      108
Fun                            84      107
Empowering                     44       46
Leader                         28       21
Popular                       154      127
Inclusive                      36       47
None of the Above              17        7

In [130]:
a = concatType1([(data.q10_proud, "Is a brand I'd be proud to be associated with"), (data.q10_me, "Is a brand for me"), 
             (data.q10_fun, "Makes beauty fun for everyone"), (data.q10_diff, "Is different from other beauty stores")
             , (data.q10_emp, "Empowers me"), (data.q10_some, "Has something for everyone")])
a = a.reindex(["Strongly Agree", "Somewhat Agree", "Neutral", "Somewhat Disagree", "Strongly Disagree", "All"])
a = breakdown(a, ["Strongly Agree", "Somewhat Agree", "Neutral", "Somewhat Disagree", "Strongly Disagree", "All"])
a = a.fillna(0)
a.to_clipboard(excel = True)
a

                  Is a brand I'd be proud to be associated with                                                       Is a brand for me                                                       Makes beauty fun for everyone                                                       Is different from other beauty stores                                                       Empowers me                                                       Has something for everyone
engager                                             Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged)       Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged)                   Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged)                           Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged) Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged)                Non-Engaged Engaged % Vertical (Non-Engaged) % Vertical (Engaged)
Strongly Agree                                             46.0    87.0                     0.18                 0.34              49.0    96.0                     0.19                 0.38                          53.0    97.0                     0.20                 0.38                                  40.0    74.0                     0.15                 0.29        26.0    68.0                     0.10                 0.27                       79.0   119.0                     0.30                 0.47
Somewhat Agree                                             88.0    88.0                     0.34                 0.35              77.0    84.0                     0.30                 0.33                         100.0    88.0                     0.38                 0.35                                  92.0    98.0                     0.35                 0.38        77.0    76.0                     0.30                 0.30                      101.0    80.0                     0.39                 0.31
Top 2                                                     134.0   175.0                     0.52                 0.69             126.0   180.0                     0.49                 0.71                         153.0   185.0                     0.58                 0.73                                 132.0   172.0                     0.50                 0.67       103.0   144.0                     0.40                 0.57                      180.0   199.0                     0.69                 0.78
Neutral                                                    92.0    67.0                     0.35                 0.26              76.0    55.0                     0.29                 0.22                          75.0    51.0                     0.29                 0.20                                  92.0    56.0                     0.35                 0.22        94.0    77.0                     0.36                 0.30                       57.0    35.0                     0.22                 0.14
Somewhat Disagree                                          22.0     9.0                     0.08                 0.04              32.0    14.0                     0.12                 0.05                          24.0    14.0                     0.09                 0.05                                  25.0    20.0                     0.10                 0.08        41.0    22.0                     0.16                 0.09                       18.0    18.0                     0.07                 0.07
Strongly Disagree                                          12.0     4.0                     0.05                 0.02              26.0     6.0                     0.10                 0.02                           8.0     5.0                     0.03                 0.02                                  11.0     7.0                     0.04                 0.03        22.0    12.0                     0.08                 0.05                        5.0     3.0                     0.02                 0.01
Bottom 2                                                   34.0    13.0                     0.13                 0.06              58.0    20.0                     0.22                 0.07                          32.0    19.0                     0.12                 0.07                                  36.0    27.0                     0.14                 0.11        63.0    34.0                     0.24                 0.14                       23.0    21.0                     0.09                 0.08
All                                                       260.0   255.0                     1.00                 1.00             260.0   255.0                     1.00                 1.00                         260.0   255.0                     1.00                 1.00                                 260.0   255.0                     1.00                 1.00       260.0   255.0                     1.00                 1.00                      260.0   255.0                     1.00                 1.00